"""empty message

Revision ID: 176bda910bd4
Revises: 2e0561e7a614
Create Date: 2020-09-25 23:11:10.639017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176bda910bd4'
down_revision = '2e0561e7a614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('using_time_day',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('using_time_month',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('using_time_year',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.drop_table('using_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('using_time',
    sa.Column('key', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(), nullable=True),
    sa.Column('time', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.drop_table('using_time_year')
    op.drop_table('using_time_month')
    op.drop_table('using_time_day')
    # ### end Alembic commands ###
