"""empty message

Revision ID: 44228c46ab17
Revises: d8295e11645e
Create Date: 2020-09-11 19:22:45.546986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44228c46ab17'
down_revision = 'd8295e11645e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('moter_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'moter_count')
    # ### end Alembic commands ###
