"""empty message

Revision ID: d8295e11645e
Revises: 
Create Date: 2020-09-11 08:15:41.678114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8295e11645e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raspberry',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('rasp_group', sa.String(length=64), nullable=False),
    sa.Column('rasp_id', sa.String(length=64), nullable=False),
    sa.Column('rasp_pw', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('device',
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('device_type', sa.String(length=64), nullable=False),
    sa.Column('onoff', sa.Boolean(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('pi_key', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pi_key'], ['raspberry.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device')
    op.drop_table('raspberry')
    # ### end Alembic commands ###
